# Generated by Django 6.1 on 2026-08-22 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('domains', models.TextField()),
                ('technologies', models.TextField()),
                ('solutions', models.TextField()),
                ('keywords', models.TextField()),
                ('target_customers', models.TextField(blank=True)),
                ('past_experience', models.TextField(blank=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('average_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eligibility_status', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('startup_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
