# Generated by Django 6.1 on 2026-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='startup_logos/'),
        ),
    ]
