# Generated by Django 6.1 on 2026-08-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startup_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('REGISTRATION', 'Registration Certificate'), ('COMPANY_PROFILE', 'Company Profile'), ('TECHNICAL', 'Technical Document'), ('FINANCIAL', 'Financial Document'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='startup_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='startups.startup')),
            ],
        ),
    ]
