# Generated by Django 6.1 on 2026-08-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startupdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='ml_startup_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
