# Generated by Django 6.1 on 2026-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startup_ml_startup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='business_stage',
            field=models.CharField(choices=[('PILOT', 'Pilot Stage'), ('SCALING', 'Scaling'), ('UNDER_REVIEW', 'Under Review')], default='UNDER_REVIEW', max_length=30),
        ),
    ]
