# Generated by Django 6.1 on 2026-08-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentdepartment',
            name='user',
        ),
    ]
