# Generated by Django 6.1 on 2026-08-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('problem_statement', models.TextField()),
                ('desired_outcome', models.TextField()),
                ('domain', models.CharField(max_length=200)),
                ('required_technologies', models.TextField(blank=True)),
                ('target_beneficiaries', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pilot_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('evaluation_criteria', models.TextField(blank=True)),
                ('kpi_requirements', models.TextField(blank=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='departments.governmentdepartment')),
            ],
        ),
    ]
