# Generated by Django 6.1 on 2026-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='pilot_duration_months',
            new_name='pilot_duration',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='evaluation_criteria',
            new_name='required_domains',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='kpi_requirements',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='target_beneficiaries',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
