# Generated by Django 6.1 on 2026-08-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_rename_pilot_duration_months_challenge_pilot_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ENGAGED', 'Engaged'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
    ]
