# Generated by Django 6.1 on 2026-08-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_title', models.CharField(max_length=250)),
                ('proposed_solution', models.TextField()),
                ('implementation_plan', models.TextField()),
                ('expected_outcomes', models.TextField()),
                ('proposed_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pilot_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='challenges.challenge')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='startups.startup')),
            ],
        ),
    ]
